window.CHINA_LNG_NEWS = {
  meta: {
    scanDate: "2026-07-10",
    scanLabel: "2026-07-10 08:29 SGT",
    topic: "China LNG demand monitor",
    note: "Source-targeted scan of public and indexed web results, organized by the demand drivers that change China's LNG call. Paid-source rows use indexed headline metadata where full text was not public. July 10 refresh added global market-context items on US/Mexico LNG, US storage and Freeport maintenance, and Hormuz diversification. The requested LinkedIn profile still blocks unauthenticated fetches with HTTP 999, so it is retained as a manual-review source.",
  },
  factors: [
    {
      id: "power-weather",
      name: "Power burn and weather",
      driver: "Cooling demand, hydro/wind availability, coal dispatch, and gas-fired generation economics determine short-run LNG upside during summer and winter peaks.",
      read: "Mixed: summer heat and reduced hydro can raise Asian LNG demand, while stronger China wind generation can still cap incremental gas burn.",
      watch: "Temperature anomalies, hydropower reservoir conditions, coastal gas-fired utilization, coal prices.",
    },
    {
      id: "price-affordability",
      name: "Spot price affordability",
      driver: "China's spot LNG demand is highly price elastic; buyers tend to retreat when JKM rises above competing pipeline, domestic gas, coal, or oil-linked term supply.",
      read: "Still cautious: Europe storage risk, Gulf uncertainty, and Asian weather can lift spot LNG prices, while ample US gas storage lowers some upstream price pressure.",
      watch: "JKM, TTF, freight, oil-linked term economics, downstream city-gate pricing.",
    },
    {
      id: "supply-mix",
      name: "Domestic and pipeline supply",
      driver: "Domestic output and pipeline imports from Russia and Central Asia can displace spot LNG while still allowing total gas demand to grow.",
      read: "Bearish for spot LNG: recent items point to pipeline and domestic supply preference.",
      watch: "Power of Siberia flows, Central Asian nominations, domestic production, pipeline infrastructure additions.",
    },
    {
      id: "transport",
      name: "Transport LNG demand",
      driver: "Heavy-truck fuel switching used to be a visible LNG demand source; electric trucks and diesel/LNG spreads can erode this demand pool.",
      read: "Bearish: electric heavy-truck adoption is pressuring LNG road-fuel use.",
      watch: "Electric heavy-truck sales, battery-swap deployment, LNG/diesel spread, road-freight activity.",
    },
    {
      id: "trade-sanctions",
      name: "Trade policy and sanctions",
      driver: "Tariffs, US-China trade détente, sanctioned Russian LNG routing, and secondary-sanction risk can redirect cargoes and affect available supply.",
      read: "Mixed: more non-Hormuz LNG routes improve portfolio optionality, while sanctioned Russian cargoes add legal and logistics risk.",
      watch: "US-China tariff treatment, Arctic LNG 2 cargo routing, terminal acceptance, shipping insurance.",
    },
    {
      id: "supply-security",
      name: "Supply security and shipping",
      driver: "Hormuz, Qatar exposure, shipping constraints, and regional disruptions influence China's willingness to buy, store, or diversify LNG.",
      read: "Chokepoint risk remains central; Pacific-route US LNG improves route diversity, but it does not guarantee China receives more cargoes.",
      watch: "Hormuz risk, Qatar liftings, freight rates, destination-flexible cargoes, storage behavior.",
    },
    {
      id: "infrastructure-storage",
      name: "Infrastructure and storage",
      driver: "Terminals, tanks, pipelines, and storage capacity affect China's ability to absorb cargoes, arbitrage seasons, and receive politically sensitive supply.",
      read: "Adds import flexibility and seasonal balancing capacity.",
      watch: "Tank construction, terminal utilization, storage injections, pipeline grid expansions.",
    },
    {
      id: "macro-policy",
      name: "Macro, policy, and end-use",
      driver: "Industrial output, city-gas policy, pricing reform, and national energy-security policy shape underlying gas demand.",
      read: "Contextual: policy signals matter, but need confirmation in monthly demand and price data.",
      watch: "Two Sessions guidance, NDRC pricing, industrial PMIs, city-gas margins.",
    },
    {
      id: "global-availability",
      name: "Global LNG availability",
      driver: "Global supply, destination-flexible cargoes, shipping, and competing Atlantic or European demand influence how much LNG is practically available to China at the clearing price.",
      read: "Mixed: Pacific-route US LNG and ample US storage ease some pressure, but Freeport maintenance, Europe pull, and Asian weather can tighten prompt cargoes.",
      watch: "US project ramp-ups, Europe storage/refill demand, GIIGNL and IGU trade data, shipping availability.",
    },
    {
      id: "expert-commentary",
      name: "Expert commentary",
      driver: "Named expert posts can flag early changes in market framing, but need authenticated review when social platforms block access.",
      read: "Manual review required for Greg Molnar's LinkedIn feed.",
      watch: "Logged-in LinkedIn review and cross-check against IEA commentary.",
    },
  ],
  coverage: [
    {
      source: "S&P Global",
      latestDate: "2026-07-10",
      status: "Indexed",
      note: "Checked again on July 10; latest relevant indexed China LNG item in the monitor remains the May 15 US oil/LNG buying headline.",
      url: "https://www.spglobal.com/commodityinsights/en/market-insights/latest-news/natural-gas",
    },
    {
      source: "Reuters",
      latestDate: "2026-07-10",
      status: "Indexed",
      note: "Checked again on July 10; latest relevant indexed China LNG items remain Russian cargo routing, China buying after the Iran shock, and electric-truck pressure.",
      url: "https://www.reuters.com/business/energy/",
    },
    {
      source: "Rystad Energy",
      latestDate: "2026-07-10",
      status: "Indexed",
      note: "Checked again on July 10; source search remains JavaScript-heavy and the latest relevant indexed item in the monitor is the Asia energy-buyer context item.",
      url: "https://www.rystadenergy.com/news",
    },
    {
      source: "Bloomberg",
      latestDate: "2026-07-10",
      status: "Indexed",
      note: "Checked again on July 10; Bloomberg story access may require subscription and the monitor retains the June China buying/import rebound items.",
      url: "https://www.bloomberg.com/energy",
    },
    {
      source: "ICIS",
      latestDate: "2026-07-10",
      status: "Indexed",
      note: "Checked again on July 10; China policy and LNG-in-transport items remain the relevant indexed ICIS headlines in the monitor.",
      url: "https://www.icis.com/explore/services/news/",
    },
    {
      source: "Global LNG Hub",
      latestDate: "2026-07-10",
      status: "Direct",
      note: "Checked again on July 10; Global LNG Hub exposes a China LNG search page and the latest direct China item in the monitor is the July 1 pipeline-gas preference report.",
      url: "https://globallnghub.com/?s=China%20LNG",
    },
    {
      source: "GIIGNL",
      latestDate: "2026-07-10",
      status: "Direct",
      note: "Checked again on July 10; GIIGNL annual report page and PDFs remain directly reachable.",
      url: "https://giignl.org/annual-report/",
    },
    {
      source: "Kpler",
      latestDate: "2026-07-10",
      status: "Indexed",
      note: "Checked again on July 10; the weather and generation item remains the relevant indexed Kpler signal.",
      url: "https://www.kpler.com/",
    },
    {
      source: "IEA",
      latestDate: "2026-07-10",
      status: "Direct",
      note: "IEA global gas market outlook provides global LNG availability and price context for China spot affordability.",
      url: "https://www.iea.org/news/growth-in-global-demand-for-natural-gas-is-set-to-accelerate-in-2026-as-lng-wave-spreads-through-markets",
    },
    {
      source: "EIA",
      latestDate: "2026-07-10",
      status: "Direct",
      note: "Checked again on July 10; EIA storage and US gas-market data are used as global availability context rather than China-specific demand sources.",
      url: "https://www.eia.gov/todayinenergy/detail.php?id=64924",
    },
    {
      source: "Wall Street Journal",
      latestDate: "2026-07-10",
      status: "Indexed",
      note: "July 7-9 natural gas and LNG-market items were used for US storage, Freeport maintenance, Europe pull, and Asian weather-risk context.",
      url: "https://www.wsj.com/news/types/commodities-futures",
    },
    {
      source: "Investor's Business Daily",
      latestDate: "2026-07-10",
      status: "Indexed",
      note: "July 9 item on the first US LNG shipment to Asia from Mexico's Energia Costa Azul terminal was used for non-Hormuz route-availability context.",
      url: "https://www.investors.com/news/lng-stocks-u-s-gas-ships-asia-mexico-win-for-trump/",
    },
    {
      source: "Axios",
      latestDate: "2026-07-10",
      status: "Indexed",
      note: "July 9 item was used for broad Hormuz diversification and US LNG demand context.",
      url: "https://www.axios.com/2026/07/09/iran-war-hormuz-oil-natural-gas-energy-transition",
    },
    {
      source: "LinkedIn / Greg Molnar",
      latestDate: "2026-07-10",
      status: "Manual",
      note: "Requested LinkedIn profile still returns HTTP 999 without authentication. Use the profile URL for logged-in/manual review.",
      url: "https://www.linkedin.com/in/greg-moln%C3%A1r-38601171/",
    },
  ],
  items: [
    {
      date: "2026-07-09",
      source: "Wall Street Journal",
      factorId: "global-availability",
      bias: "Mixed availability",
      biasTone: "context",
      headline: "U.S. Natural Gas Falls Hit By Storage, LNG Maintenance Issues",
      readthrough: "A larger US storage build lowers some upstream gas-price pressure, while Freeport LNG maintenance can temporarily reduce export availability.",
      action: "Track Freeport maintenance duration, US feedgas demand, and whether lower Henry Hub costs translate into lower delivered Asia LNG prices.",
      access: "Indexed headline; WSJ access may be required",
      url: "https://www.wsj.com/finance/commodities-futures/u-s-natural-gas-futures-held-back-by-adequate-supply-7345b617",
    },
    {
      date: "2026-07-09",
      source: "Investor's Business Daily",
      factorId: "supply-security",
      bias: "Route optionality",
      biasTone: "context",
      headline: "First U.S. LNG Ships To Asia From Mexico, Avoiding Hormuz Tensions",
      readthrough: "Mexico's Pacific-coast LNG route gives Asian buyers a shorter non-Hormuz pathway for US-linked LNG, but cargo allocation to China still depends on netbacks and contracts.",
      action: "Watch ECA cargo destinations, delivered Asia pricing, and whether Chinese buyers can access destination-flexible volumes.",
      access: "Indexed public news result",
      url: "https://www.investors.com/news/lng-stocks-u-s-gas-ships-asia-mexico-win-for-trump/",
    },
    {
      date: "2026-07-09",
      source: "Axios",
      factorId: "trade-sanctions",
      bias: "Diversification context",
      biasTone: "context",
      headline: "The Iran war's limited boost for energy transition",
      readthrough: "The war is reinforcing demand for diversified energy routes and US LNG, but the shift is more about supply security than immediate China LNG demand.",
      action: "Track whether Chinese portfolios prioritize non-Hormuz supply optionality in new term talks or spot procurement.",
      access: "Indexed public news result",
      url: "https://www.axios.com/2026/07/09/iran-war-hormuz-oil-natural-gas-energy-transition",
    },
    {
      date: "2026-07-08",
      source: "Wall Street Journal",
      factorId: "price-affordability",
      bias: "Tightens prompt pricing",
      biasTone: "risk",
      headline: "European gas prices rise as U.S.-Iran tensions add to supply concerns ahead of winter",
      readthrough: "Higher European gas prices and storage concern can pull flexible LNG toward Europe, lifting the price China must pay for spot cargoes.",
      action: "Watch TTF-JKM spreads, European storage injections, and whether China retreats from spot tenders when Europe bids up flexible supply.",
      access: "Indexed headline; WSJ access may be required",
      url: "https://www.wsj.com/articles/european-gas-prices-rise-as-u-s-iran-tensions-add-to-supply-concerns-ahead-of-winter-f8ed362e",
    },
    {
      date: "2026-07-07",
      source: "Wall Street Journal",
      factorId: "power-weather",
      bias: "Raises weather risk",
      biasTone: "risk",
      headline: "U.S. Natural Gas Futures Rise on Summer Demand",
      readthrough: "The indexed market note flags Asian LNG demand risk from El Nino-linked weather and reduced hydro output, reinforcing weather as the main upside risk to summer LNG call.",
      action: "Cross-check China temperature anomalies, hydro output, wind generation, and coastal gas-fired power burn before changing demand assumptions.",
      access: "Indexed headline; WSJ access may be required",
      url: "https://www.wsj.com/articles/european-gas-slips-but-lng-flow-recovery-and-asian-demand-risks-persist-29b2094a",
    },
    {
      date: "2026-07-02",
      source: "Kpler",
      factorId: "power-weather",
      bias: "Caps LNG demand",
      biasTone: "cap",
      headline: "El Nino to modestly lift China's wind generation, offsetting hydro weakness and capping LNG demand",
      readthrough: "A stronger wind signal offsets some hydro weakness, reducing the amount of incremental gas-fired power generation needed during weather stress.",
      action: "Track wind output and hydro conditions before treating heat as automatically bullish for LNG.",
      access: "Indexed headline; Kpler access may be required",
      url: "https://news.google.com/search?q=%22El%20Nino%20to%20modestly%20lift%20China%27s%20wind%20generation%22%20Kpler",
    },
    {
      date: "2026-07-01",
      source: "Global LNG Hub",
      factorId: "supply-mix",
      bias: "Caps spot LNG",
      biasTone: "cap",
      headline: "China LNG imports weaken as buyers favour pipeline gas",
      readthrough: "Chinese buyers are favoring pipeline gas, domestic supply, and term cargoes over spot LNG.",
      action: "Check whether JODI LNG actuals and customs LNG tonnage confirm lower spot-linked demand.",
      access: "Direct public summary",
      url: "https://globallnghub.com/report-presentation/china-lng-imports-weaken-as-buyers-favour-pipeline-gas",
    },
    {
      date: "2026-06-30",
      source: "Global LNG Hub",
      factorId: "global-availability",
      bias: "Availability context",
      biasTone: "context",
      headline: "Global LNG supply grew by 2% in June 2026 despite Hormuz disruption",
      readthrough: "Global supply resilience can lower price pressure, but it does not guarantee incremental cargoes clear into China.",
      action: "Compare global supply growth with JKM and Chinese spot tender activity.",
      access: "Direct public report page",
      url: "https://globallnghub.com/global-lng-supply-grew-by-2-in-june-2026-despite-hormuz-disruption.html",
    },
    {
      date: "2026-06-22",
      source: "Reuters",
      factorId: "trade-sanctions",
      bias: "Mixed / risk",
      biasTone: "risk",
      headline: "EXCLUSIVE: China lines up second LNG terminal for sanctioned Russian cargoes, sources say",
      readthrough: "Additional terminal optionality may improve cargo-routing flexibility, but sanctioned Russian supply carries legal, insurance, and logistics risk.",
      action: "Watch sanctioned Russian LNG discharge patterns, terminal routing, and secondary-sanction risk.",
      access: "Indexed headline; Reuters access may be required",
      url: "https://news.google.com/search?q=%22China%20lines%20up%20second%20LNG%20terminal%20for%20sanctioned%20Russian%20cargoes%22%20Reuters",
    },
    {
      date: "2026-06-21",
      source: "Pipeline and Gas Journal",
      factorId: "infrastructure-storage",
      bias: "Adds flexibility",
      biasTone: "support",
      headline: "PipeChina, GTT to Build World's Largest LNG Storage Tanks in China",
      readthrough: "More storage capacity increases seasonal balancing capability and can make opportunistic LNG purchases easier to absorb.",
      action: "Track project timeline, connected terminal capacity, and whether tanks are commercial or strategic storage.",
      access: "Indexed headline",
      url: "https://news.google.com/search?q=%22PipeChina%2C%20GTT%20to%20Build%20World%27s%20Largest%20LNG%20Storage%20Tanks%20in%20China%22",
    },
    {
      date: "2026-06-15",
      source: "Reuters",
      factorId: "transport",
      bias: "Caps LNG demand",
      biasTone: "cap",
      headline: "China sets sights on heavy truck electrification in blow to diesel demand",
      readthrough: "Heavy-truck electrification also pressures LNG truck-fuel demand where LNG competes with diesel in long-haul freight.",
      action: "Track LNG truck sales, electric truck penetration, and freight activity by province.",
      access: "Indexed headline; Reuters access may be required",
      url: "https://news.google.com/search?q=%22China%20sets%20sights%20on%20heavy%20truck%20electrification%20in%20blow%20to%20diesel%20demand%22%20Reuters",
    },
    {
      date: "2026-06-09",
      source: "Reuters",
      factorId: "power-weather",
      bias: "Raises LNG call",
      biasTone: "support",
      headline: "LNG demand in Asia recovers from Iran shock as China buys",
      readthrough: "Chinese buying was cited as part of an Asian demand recovery after Middle East disruption.",
      action: "Compare spot price moves with Chinese cargo arrivals and summer power-sector gas demand.",
      access: "Indexed headline; Reuters access may be required",
      url: "https://news.google.com/search?q=%22LNG%20demand%20in%20Asia%20recovers%20from%20Iran%20shock%20as%20China%20buys%22%20Reuters",
    },
    {
      date: "2026-06-08",
      source: "Bloomberg",
      factorId: "power-weather",
      bias: "Raises LNG call",
      biasTone: "support",
      headline: "China Ramping Up LNG Buying in Anticipation of Summer Heat",
      readthrough: "Summer cooling demand can lift gas-fired power burn and prompt LNG restocking.",
      action: "Monitor weather, power burn, and coastal terminal sendout for confirmation.",
      access: "Indexed headline; Bloomberg access may be required",
      url: "https://news.google.com/search?q=%22China%20Ramping%20Up%20LNG%20Buying%20in%20Anticipation%20of%20Summer%20Heat%22%20Bloomberg",
    },
    {
      date: "2026-06-01",
      source: "Bloomberg",
      factorId: "power-weather",
      bias: "Raises LNG call",
      biasTone: "support",
      headline: "China's LNG Imports Rebound in May as Buyers Prepare for Summer",
      readthrough: "A May import rebound points to seasonal preparation for warmer-weather demand.",
      action: "Check whether May rebound is sustained into June and July or remains seasonal restocking.",
      access: "Indexed headline; Bloomberg access may be required",
      url: "https://news.google.com/search?q=%22China%27s%20LNG%20Imports%20Rebound%20in%20May%20as%20Buyers%20Prepare%20for%20Summer%22%20Bloomberg",
    },
    {
      date: "2026-05-26",
      source: "Global LNG Hub",
      factorId: "supply-mix",
      bias: "Caps spot LNG",
      biasTone: "cap",
      headline: "Russian gas exports to China expand as pipelines and LNG reshape supply routes",
      readthrough: "More Russian pipeline and LNG optionality can reduce China's need for non-Russian spot LNG when economics favor alternatives.",
      action: "Track Power of Siberia nominations and Russian LNG arrivals by receiving terminal.",
      access: "Direct public report page",
      url: "https://globallnghub.com/report-presentation/russian-gas-exports-to-china-expand-as-pipelines-and-lng-reshape-supply-routes",
    },
    {
      date: "2026-05-15",
      source: "S&P Global",
      factorId: "trade-sanctions",
      bias: "Improves supply diversity",
      biasTone: "support",
      headline: "Trump says China wants to buy US oil and LNG after Beijing talks",
      readthrough: "A US-China trade thaw could reopen US LNG flows into China and improve portfolio flexibility.",
      action: "Watch for tariff relief, resumed US cargoes, and term-contract nominations into Chinese terminals.",
      access: "Indexed headline; S&P Global access may be required",
      url: "https://news.google.com/search?q=%22Trump%20says%20China%20wants%20to%20buy%20US%20oil%20and%20LNG%20after%20Beijing%20talks%22%20%22S%26P%20Global%22",
    },
    {
      date: "2026-04-16",
      source: "EIA",
      factorId: "global-availability",
      bias: "Lowers price pressure",
      biasTone: "support",
      headline: "US natural gas exports to grow nearly 30% by 2027 as LNG facilities ramp up",
      readthrough: "More US LNG supply can ease global market conditions over time, but Chinese uptake still depends on netbacks, tariffs, contract terms, and buyer appetite.",
      action: "Track US project ramp-ups, destination-flexible cargo availability, and whether Asia pricing clears above Atlantic alternatives.",
      access: "Direct public source",
      url: "https://www.eia.gov/todayinenergy/detail.php?id=64924",
    },
    {
      date: "2026-04-14",
      source: "Rystad Energy",
      factorId: "price-affordability",
      bias: "Mixed / buyer risk",
      biasTone: "risk",
      headline: "Asia's Energy Buyers: Between a Rock and a Hard Place",
      readthrough: "Regional buyers face price, supply-security, and policy tradeoffs that shape China's spot LNG participation.",
      action: "Use as context for Chinese buyer sensitivity to price, security, and shipping constraints.",
      access: "Indexed headline; direct page not server-rendered in scan",
      url: "https://news.google.com/search?q=%22Asia%27s%20Energy%20Buyers%3A%20Between%20a%20Rock%20and%20a%20Hard%20Place%22%20%22Rystad%20Energy%22",
    },
    {
      date: "2026-03-11",
      source: "Global LNG Hub",
      factorId: "supply-security",
      bias: "Security risk",
      biasTone: "risk",
      headline: "Strait of Hormuz disruption could reshape China's LNG supply security",
      readthrough: "Hormuz risk can lift security-driven stocking and diversification, while also raising spot prices.",
      action: "Stress-test China exposure to Qatar and Middle East LNG against pipeline and Russian supply alternatives.",
      access: "Direct public report page",
      url: "https://globallnghub.com/report-presentation/strait-of-hormuz-disruption-could-reshape-chinas-lng-supply-security",
    },
    {
      date: "2026-03-04",
      source: "ICIS",
      factorId: "macro-policy",
      bias: "Policy context",
      biasTone: "context",
      headline: "What to watch for energy policy in China's Two Sessions",
      readthrough: "Energy policy signals can affect gas pricing, infrastructure, and import appetite, but need confirmation in data.",
      action: "Check gas pricing, import, and infrastructure policy signals against demand-side assumptions.",
      access: "Indexed headline; ICIS access may be required",
      url: "https://news.google.com/search?q=%22What%20to%20watch%20for%20energy%20policy%20in%20China%27s%20Two%20Sessions%22%20ICIS",
    },
    {
      date: "2026-03-03",
      source: "S&P Global",
      factorId: "price-affordability",
      bias: "Caps spot LNG",
      biasTone: "cap",
      headline: "China faces LNG supply test amid Middle East crisis, spot price increase",
      readthrough: "Middle East disruption and higher spot prices test China's willingness to buy prompt LNG.",
      action: "Watch spot price ceilings for Chinese buyers and any switch toward pipelines or domestic gas.",
      access: "Indexed headline; S&P Global access may be required",
      url: "https://news.google.com/search?q=%22China%20faces%20LNG%20supply%20test%20amid%20Middle%20East%20crisis%2C%20spot%20price%20increase%22%20%22S%26P%20Global%22",
    },
    {
      date: "2026-02-12",
      source: "ICIS",
      factorId: "transport",
      bias: "Caps LNG demand",
      biasTone: "cap",
      headline: "China's shift to electric heavy trucks pressures LNG use in transport",
      readthrough: "Electric heavy trucks reduce one of the more price-responsive pockets of LNG demand.",
      action: "Review whether road-fuel LNG weakness changes city-gas and transport demand allocation assumptions.",
      access: "Indexed headline; ICIS access may be required",
      url: "https://news.google.com/search?q=%22China%27s%20shift%20to%20electric%20heavy%20trucks%20pressures%20LNG%20use%20in%20transport%22%20ICIS",
    },
    {
      date: "2026-01-23",
      source: "IEA",
      factorId: "global-availability",
      bias: "Context",
      biasTone: "context",
      headline: "Growth in global demand for natural gas is set to accelerate in 2026 as LNG wave spreads through markets",
      readthrough: "The LNG supply wave can pressure global prices lower, but allocation to China depends on relative netbacks and buyer appetite.",
      action: "Use IEA global market assumptions as a cross-check on JKM affordability scenarios.",
      access: "Direct public source",
      url: "https://www.iea.org/news/growth-in-global-demand-for-natural-gas-is-set-to-accelerate-in-2026-as-lng-wave-spreads-through-markets",
    },
    {
      date: "2026-07-08",
      source: "GIIGNL",
      factorId: "global-availability",
      bias: "Context",
      biasTone: "context",
      headline: "GIIGNL annual report library refreshed with latest LNG market report PDFs",
      readthrough: "GIIGNL provides importer rankings, global trade totals, and China share context for periodic monitor refreshes.",
      action: "Use GIIGNL for annual import-share benchmarking and global trade context.",
      access: "Direct public report page and PDFs",
      url: "https://giignl.org/annual-report/",
    },
    {
      date: "2026-07-10",
      source: "LinkedIn / Greg Molnar",
      factorId: "expert-commentary",
      bias: "Manual review",
      biasTone: "manual",
      headline: "Greg Molnar LinkedIn posts require authenticated/manual review",
      readthrough: "The requested LinkedIn profile and recent-activity URL still block unauthenticated fetches with HTTP 999, so no post text was captured in this automated scan.",
      action: "Open the profile while logged in and add any China LNG post summaries during the next manual monitor pass.",
      access: "Manual profile link",
      url: "https://www.linkedin.com/in/greg-moln%C3%A1r-38601171/",
    },
  ],
};
