window.CHINA_LNG_NEWS = {
  meta: {
    scanDate: "2026-07-09",
    scanLabel: "2026-07-09 17:14 SGT",
    topic: "China LNG news",
    note: "Source-targeted scan of public and indexed web results. Paid-source rows use indexed headline metadata where full text was not public. The requested LinkedIn profile blocked unauthenticated fetches with HTTP 999, so it is retained as a manual-review source.",
  },
  coverage: [
    {
      source: "S&P Global",
      latestDate: "2026-05-15",
      status: "Indexed",
      note: "Current S&P Global China/LNG headlines were found through Google News metadata; full text may require subscription.",
      url: "https://www.spglobal.com/commodityinsights/en/market-insights/latest-news/natural-gas",
    },
    {
      source: "Reuters",
      latestDate: "2026-06-22",
      status: "Indexed",
      note: "Multiple China LNG headlines were found, including Russian cargo routing and China buying after the Iran shock.",
      url: "https://www.reuters.com/business/energy/",
    },
    {
      source: "Rystad Energy",
      latestDate: "2026-04-14",
      status: "Indexed",
      note: "Rystad source search is JavaScript-heavy; Google News exposed the relevant Asia energy buyer item.",
      url: "https://www.rystadenergy.com/news",
    },
    {
      source: "Bloomberg",
      latestDate: "2026-06-08",
      status: "Indexed",
      note: "Several China LNG demand/import rebound headlines were found; Bloomberg story access may require subscription.",
      url: "https://www.bloomberg.com/energy",
    },
    {
      source: "ICIS",
      latestDate: "2026-03-04",
      status: "Indexed",
      note: "China policy and LNG-in-transport items were found through indexed ICIS headlines.",
      url: "https://www.icis.com/explore/services/news/",
    },
    {
      source: "Global LNG Hub",
      latestDate: "2026-07-01",
      status: "Direct",
      note: "Global LNG Hub exposes a China LNG search page and direct report pages.",
      url: "https://globallnghub.com/?s=China%20LNG",
    },
    {
      source: "GIIGNL",
      latestDate: "2026-07-08",
      status: "Direct",
      note: "GIIGNL annual report page and PDFs were directly reachable; page last published on July 8, 2026.",
      url: "https://giignl.org/annual-report/",
    },
    {
      source: "LinkedIn / Greg Molnar",
      latestDate: "2026-07-09",
      status: "Manual",
      note: "Requested LinkedIn profile blocked unauthenticated access. Use the profile URL for logged-in/manual review.",
      url: "https://www.linkedin.com/in/greg-moln%C3%A1r-38601171/",
    },
  ],
  items: [
    {
      date: "2026-07-01",
      source: "Global LNG Hub",
      theme: "Demand / imports",
      priority: "High",
      headline: "China LNG imports weaken as buyers favour pipeline gas",
      summary: "Highlights weaker spot LNG appetite as Chinese buyers favor pipeline gas, domestic supply, and term cargoes.",
      action: "Track whether JODI LNG actuals and customs LNG tonnage confirm lower spot-linked demand.",
      access: "Direct public summary",
      url: "https://globallnghub.com/report-presentation/china-lng-imports-weaken-as-buyers-favour-pipeline-gas",
    },
    {
      date: "2026-06-22",
      source: "Reuters",
      theme: "Russia supply",
      priority: "High",
      headline: "EXCLUSIVE: China lines up second LNG terminal for sanctioned Russian cargoes, sources say",
      summary: "Signals China may be adding receiving options for sanctioned Russian-origin LNG cargoes.",
      action: "Watch sanctioned Russian LNG discharge patterns, terminal routing, and secondary-sanction risk.",
      access: "Indexed headline; Reuters access may be required",
      url: "https://news.google.com/search?q=%22China%20lines%20up%20second%20LNG%20terminal%20for%20sanctioned%20Russian%20cargoes%22%20Reuters",
    },
    {
      date: "2026-06-09",
      source: "Reuters",
      theme: "Spot demand",
      priority: "High",
      headline: "LNG demand in Asia recovers from Iran shock as China buys",
      summary: "Chinese buying was cited as part of an Asian demand recovery after Middle East disruption.",
      action: "Compare spot price moves with Chinese cargo arrivals and summer power-sector gas demand.",
      access: "Indexed headline; Reuters access may be required",
      url: "https://news.google.com/search?q=%22LNG%20demand%20in%20Asia%20recovers%20from%20Iran%20shock%20as%20China%20buys%22%20Reuters",
    },
    {
      date: "2026-06-08",
      source: "Bloomberg",
      theme: "Summer demand",
      priority: "High",
      headline: "China Ramping Up LNG Buying in Anticipation of Summer Heat",
      summary: "Bloomberg indexed a pickup in China LNG buying ahead of summer heat-driven demand.",
      action: "Monitor weather, power burn, and coastal terminal sendout for confirmation.",
      access: "Indexed headline; Bloomberg access may be required",
      url: "https://news.google.com/search?q=%22China%20Ramping%20Up%20LNG%20Buying%20in%20Anticipation%20of%20Summer%20Heat%22%20Bloomberg",
    },
    {
      date: "2026-06-01",
      source: "Bloomberg",
      theme: "Imports",
      priority: "Medium",
      headline: "China's LNG Imports Rebound in May as Buyers Prepare for Summer",
      summary: "Points to a May import rebound as buyers prepared for warmer-weather demand.",
      action: "Check whether May rebound is sustained into June and July or remains seasonal restocking.",
      access: "Indexed headline; Bloomberg access may be required",
      url: "https://news.google.com/search?q=%22China%27s%20LNG%20Imports%20Rebound%20in%20May%20as%20Buyers%20Prepare%20for%20Summer%22%20Bloomberg",
    },
    {
      date: "2026-05-15",
      source: "S&P Global",
      theme: "US-China trade",
      priority: "High",
      headline: "Trump says China wants to buy US oil and LNG after Beijing talks",
      summary: "Indexed S&P Global item raises the prospect of renewed China interest in US LNG following talks.",
      action: "Watch for tariff relief, resumed US cargoes, and term-contract nominations into Chinese terminals.",
      access: "Indexed headline; S&P Global access may be required",
      url: "https://news.google.com/search?q=%22Trump%20says%20China%20wants%20to%20buy%20US%20oil%20and%20LNG%20after%20Beijing%20talks%22%20%22S%26P%20Global%22",
    },
    {
      date: "2026-04-14",
      source: "Rystad Energy",
      theme: "Asia buyer risk",
      priority: "Medium",
      headline: "Asia's Energy Buyers: Between a Rock and a Hard Place",
      summary: "Rystad Energy indexed a regional buyer-risk readout relevant to China's LNG procurement choices.",
      action: "Use as regional context for Chinese buyer sensitivity to price, security, and shipping constraints.",
      access: "Indexed headline; direct page not server-rendered in scan",
      url: "https://news.google.com/search?q=%22Asia%27s%20Energy%20Buyers%3A%20Between%20a%20Rock%20and%20a%20Hard%20Place%22%20%22Rystad%20Energy%22",
    },
    {
      date: "2026-03-11",
      source: "Global LNG Hub",
      theme: "Supply security",
      priority: "High",
      headline: "Strait of Hormuz disruption could reshape China's LNG supply security",
      summary: "Frames Hormuz risk as a direct China LNG security issue.",
      action: "Stress-test China exposure to Qatar and Middle East LNG against pipeline and Russian supply alternatives.",
      access: "Direct public report page",
      url: "https://globallnghub.com/report-presentation/strait-of-hormuz-disruption-could-reshape-chinas-lng-supply-security",
    },
    {
      date: "2026-03-04",
      source: "ICIS",
      theme: "Policy",
      priority: "Medium",
      headline: "What to watch for energy policy in China's Two Sessions",
      summary: "ICIS indexed China energy-policy watchpoints around the Two Sessions period.",
      action: "Check gas pricing, import, and infrastructure policy signals against demand-side assumptions.",
      access: "Indexed headline; ICIS access may be required",
      url: "https://news.google.com/search?q=%22What%20to%20watch%20for%20energy%20policy%20in%20China%27s%20Two%20Sessions%22%20ICIS",
    },
    {
      date: "2026-03-03",
      source: "S&P Global",
      theme: "Supply security",
      priority: "High",
      headline: "China faces LNG supply test amid Middle East crisis, spot price increase",
      summary: "S&P Global indexed a China LNG supply-risk item tied to Middle East disruption and spot price increases.",
      action: "Watch spot price ceilings for Chinese buyers and any switch toward pipelines or domestic gas.",
      access: "Indexed headline; S&P Global access may be required",
      url: "https://news.google.com/search?q=%22China%20faces%20LNG%20supply%20test%20amid%20Middle%20East%20crisis%2C%20spot%20price%20increase%22%20%22S%26P%20Global%22",
    },
    {
      date: "2026-02-12",
      source: "ICIS",
      theme: "Transport demand",
      priority: "Medium",
      headline: "China's shift to electric heavy trucks pressures LNG use in transport",
      summary: "ICIS indexed a direct China LNG demand-side item: electric heavy trucks pressuring LNG transport use.",
      action: "Review whether road-fuel LNG weakness changes city-gas and transport demand allocation assumptions.",
      access: "Indexed headline; ICIS access may be required",
      url: "https://news.google.com/search?q=%22China%27s%20shift%20to%20electric%20heavy%20trucks%20pressures%20LNG%20use%20in%20transport%22%20ICIS",
    },
    {
      date: "2026-07-08",
      source: "GIIGNL",
      theme: "Market statistics",
      priority: "Medium",
      headline: "GIIGNL annual report library refreshed with latest LNG market report PDFs",
      summary: "GIIGNL's annual report page was directly reachable and last published on July 8, 2026; the library includes the latest LNG market report PDFs.",
      action: "Use GIIGNL for importer rankings, global trade totals, and China share context in periodic refreshes.",
      access: "Direct public report page and PDFs",
      url: "https://giignl.org/annual-report/",
    },
    {
      date: "2026-07-09",
      source: "LinkedIn / Greg Molnar",
      theme: "Expert posts",
      priority: "Manual",
      headline: "Greg Molnar LinkedIn posts require authenticated/manual review",
      summary: "The requested LinkedIn profile and recent-activity URL blocked unauthenticated fetches with HTTP 999, so no post text was captured in this automated scan.",
      action: "Open the profile while logged in and add any China LNG post summaries during the next manual monitor pass.",
      access: "Manual profile link",
      url: "https://www.linkedin.com/in/greg-moln%C3%A1r-38601171/",
    },
  ],
};
