window.CHINA_LNG_NEWS = {
  meta: {
    scanDate: "2026-07-09",
    scanLabel: "2026-07-09 19:55 SGT",
    topic: "China LNG demand monitor",
    note: "Source-targeted scan of public and indexed web results, organized by the demand drivers that change China's LNG call. Paid-source rows use indexed headline metadata where full text was not public. The requested LinkedIn profile blocked unauthenticated fetches with HTTP 999, so it is retained as a manual-review source.",
  },
  factors: [
    {
      id: "power-weather",
      name: "Power burn and weather",
      driver: "Cooling demand, hydro/wind availability, coal dispatch, and gas-fired generation economics determine short-run LNG upside during summer and winter peaks.",
      read: "Mixed: summer heat supports LNG buying, but better wind generation can cap incremental gas burn.",
      watch: "Temperature anomalies, hydropower reservoir conditions, coastal gas-fired utilization, coal prices.",
    },
    {
      id: "price-affordability",
      name: "Spot price affordability",
      driver: "China's spot LNG demand is highly price elastic; buyers tend to retreat when JKM rises above competing pipeline, domestic gas, coal, or oil-linked term supply.",
      read: "Mostly bearish for spot LNG when Middle East risk pushes prices higher.",
      watch: "JKM, TTF, freight, oil-linked term economics, downstream city-gate pricing.",
    },
    {
      id: "supply-mix",
      name: "Domestic and pipeline supply",
      driver: "Domestic output and pipeline imports from Russia and Central Asia can displace spot LNG while still allowing total gas demand to grow.",
      read: "Bearish for spot LNG: recent items point to pipeline and domestic supply preference.",
      watch: "Power of Siberia flows, Central Asian nominations, domestic production, pipeline infrastructure additions.",
    },
    {
      id: "transport",
      name: "Transport LNG demand",
      driver: "Heavy-truck fuel switching used to be a visible LNG demand source; electric trucks and diesel/LNG spreads can erode this demand pool.",
      read: "Bearish: electric heavy-truck adoption is pressuring LNG road-fuel use.",
      watch: "Electric heavy-truck sales, battery-swap deployment, LNG/diesel spread, road-freight activity.",
    },
    {
      id: "trade-sanctions",
      name: "Trade policy and sanctions",
      driver: "Tariffs, US-China trade détente, sanctioned Russian LNG routing, and secondary-sanction risk can redirect cargoes and affect available supply.",
      read: "Mixed: US LNG reopening would help supply diversity, while sanctioned Russian cargoes add legal and logistics risk.",
      watch: "US-China tariff treatment, Arctic LNG 2 cargo routing, terminal acceptance, shipping insurance.",
    },
    {
      id: "supply-security",
      name: "Supply security and shipping",
      driver: "Hormuz, Qatar exposure, shipping constraints, and regional disruptions influence China's willingness to buy, store, or diversify LNG.",
      read: "Risk supportive for preparedness, but price spikes can suppress spot purchases.",
      watch: "Hormuz risk, Qatar liftings, freight rates, destination-flexible cargoes, storage behavior.",
    },
    {
      id: "infrastructure-storage",
      name: "Infrastructure and storage",
      driver: "Terminals, tanks, pipelines, and storage capacity affect China's ability to absorb cargoes, arbitrage seasons, and receive politically sensitive supply.",
      read: "Supportive for import flexibility and seasonal balancing.",
      watch: "Tank construction, terminal utilization, storage injections, pipeline grid expansions.",
    },
    {
      id: "macro-policy",
      name: "Macro, policy, and end-use",
      driver: "Industrial output, city-gas policy, pricing reform, and national energy-security policy shape underlying gas demand.",
      read: "Contextual: policy signals matter, but need confirmation in monthly demand and price data.",
      watch: "Two Sessions guidance, NDRC pricing, industrial PMIs, city-gas margins.",
    },
    {
      id: "global-balance",
      name: "Global LNG balance",
      driver: "Global supply growth, European pull, new US LNG, and LNG trade statistics influence prices and therefore China's spot affordability.",
      read: "Potentially supportive from new supply, but competition from Europe can tighten prompt balances.",
      watch: "US project ramp-ups, Europe storage/refill demand, GIIGNL and IGU trade data, shipping availability.",
    },
    {
      id: "expert-commentary",
      name: "Expert commentary",
      driver: "Named expert posts can flag early changes in market framing, but need authenticated review when social platforms block access.",
      read: "Manual review required for Greg Molnar's LinkedIn feed.",
      watch: "Logged-in LinkedIn review and cross-check against IEA commentary.",
    },
  ],
  coverage: [
    {
      source: "S&P Global",
      latestDate: "2026-05-15",
      status: "Indexed",
      note: "Current S&P Global China/LNG headlines were found through Google News metadata; full text may require subscription.",
      url: "https://www.spglobal.com/commodityinsights/en/market-insights/latest-news/natural-gas",
    },
    {
      source: "Reuters",
      latestDate: "2026-06-22",
      status: "Indexed",
      note: "Multiple China LNG headlines were found, including Russian cargo routing, China buying after the Iran shock, and electric-truck pressure.",
      url: "https://www.reuters.com/business/energy/",
    },
    {
      source: "Rystad Energy",
      latestDate: "2026-04-14",
      status: "Indexed",
      note: "Rystad source search is JavaScript-heavy; Google News exposed the relevant Asia energy buyer item.",
      url: "https://www.rystadenergy.com/news",
    },
    {
      source: "Bloomberg",
      latestDate: "2026-06-08",
      status: "Indexed",
      note: "Several China LNG demand/import rebound headlines were found; Bloomberg story access may require subscription.",
      url: "https://www.bloomberg.com/energy",
    },
    {
      source: "ICIS",
      latestDate: "2026-03-04",
      status: "Indexed",
      note: "China policy and LNG-in-transport items were found through indexed ICIS headlines.",
      url: "https://www.icis.com/explore/services/news/",
    },
    {
      source: "Global LNG Hub",
      latestDate: "2026-07-01",
      status: "Direct",
      note: "Global LNG Hub exposes a China LNG search page and direct report pages.",
      url: "https://globallnghub.com/?s=China%20LNG",
    },
    {
      source: "GIIGNL",
      latestDate: "2026-07-08",
      status: "Direct",
      note: "GIIGNL annual report page and PDFs were directly reachable; page last published on July 8, 2026.",
      url: "https://giignl.org/annual-report/",
    },
    {
      source: "Kpler",
      latestDate: "2026-07-02",
      status: "Indexed",
      note: "Kpler weather and generation item was found through indexed Google News metadata.",
      url: "https://www.kpler.com/",
    },
    {
      source: "IEA",
      latestDate: "2026-01-23",
      status: "Direct",
      note: "IEA global gas market outlook provides global LNG balance context for China spot affordability.",
      url: "https://www.iea.org/news/growth-in-global-demand-for-natural-gas-is-set-to-accelerate-in-2026-as-lng-wave-spreads-through-markets",
    },
    {
      source: "EIA",
      latestDate: "2026-04-16",
      status: "Direct",
      note: "EIA US export outlook is used as global supply context rather than a China-specific demand source.",
      url: "https://www.eia.gov/todayinenergy/detail.php?id=64924",
    },
    {
      source: "LinkedIn / Greg Molnar",
      latestDate: "2026-07-09",
      status: "Manual",
      note: "Requested LinkedIn profile blocked unauthenticated access. Use the profile URL for logged-in/manual review.",
      url: "https://www.linkedin.com/in/greg-moln%C3%A1r-38601171/",
    },
  ],
  items: [
    {
      date: "2026-07-02",
      source: "Kpler",
      factorId: "power-weather",
      bias: "Caps LNG demand",
      biasTone: "cap",
      headline: "El Nino to modestly lift China's wind generation, offsetting hydro weakness and capping LNG demand",
      readthrough: "A stronger wind signal offsets some hydro weakness, reducing the amount of incremental gas-fired power generation needed during weather stress.",
      action: "Track wind output and hydro conditions before treating heat as automatically bullish for LNG.",
      access: "Indexed headline; Kpler access may be required",
      url: "https://news.google.com/search?q=%22El%20Nino%20to%20modestly%20lift%20China%27s%20wind%20generation%22%20Kpler",
    },
    {
      date: "2026-07-01",
      source: "Global LNG Hub",
      factorId: "supply-mix",
      bias: "Caps spot LNG",
      biasTone: "cap",
      headline: "China LNG imports weaken as buyers favour pipeline gas",
      readthrough: "Chinese buyers are favoring pipeline gas, domestic supply, and term cargoes over spot LNG.",
      action: "Check whether JODI LNG actuals and customs LNG tonnage confirm lower spot-linked demand.",
      access: "Direct public summary",
      url: "https://globallnghub.com/report-presentation/china-lng-imports-weaken-as-buyers-favour-pipeline-gas",
    },
    {
      date: "2026-06-30",
      source: "Global LNG Hub",
      factorId: "global-balance",
      bias: "Context",
      biasTone: "context",
      headline: "Global LNG supply grew by 2% in June 2026 despite Hormuz disruption",
      readthrough: "Global supply resilience can soften the price impact of geopolitical disruption, improving China spot affordability at the margin.",
      action: "Compare global supply growth with JKM and Chinese spot tender activity.",
      access: "Direct public report page",
      url: "https://globallnghub.com/global-lng-supply-grew-by-2-in-june-2026-despite-hormuz-disruption.html",
    },
    {
      date: "2026-06-22",
      source: "Reuters",
      factorId: "trade-sanctions",
      bias: "Mixed / risk",
      biasTone: "risk",
      headline: "EXCLUSIVE: China lines up second LNG terminal for sanctioned Russian cargoes, sources say",
      readthrough: "Additional terminal optionality may improve cargo-routing flexibility, but sanctioned Russian supply carries legal, insurance, and logistics risk.",
      action: "Watch sanctioned Russian LNG discharge patterns, terminal routing, and secondary-sanction risk.",
      access: "Indexed headline; Reuters access may be required",
      url: "https://news.google.com/search?q=%22China%20lines%20up%20second%20LNG%20terminal%20for%20sanctioned%20Russian%20cargoes%22%20Reuters",
    },
    {
      date: "2026-06-21",
      source: "Pipeline and Gas Journal",
      factorId: "infrastructure-storage",
      bias: "Supports flexibility",
      biasTone: "support",
      headline: "PipeChina, GTT to Build World's Largest LNG Storage Tanks in China",
      readthrough: "More storage capacity increases seasonal balancing capability and can make opportunistic LNG purchases easier to absorb.",
      action: "Track project timeline, connected terminal capacity, and whether tanks support commercial or strategic storage.",
      access: "Indexed headline",
      url: "https://news.google.com/search?q=%22PipeChina%2C%20GTT%20to%20Build%20World%27s%20Largest%20LNG%20Storage%20Tanks%20in%20China%22",
    },
    {
      date: "2026-06-15",
      source: "Reuters",
      factorId: "transport",
      bias: "Caps LNG demand",
      biasTone: "cap",
      headline: "China sets sights on heavy truck electrification in blow to diesel demand",
      readthrough: "Heavy-truck electrification also pressures LNG truck-fuel demand where LNG competes with diesel in long-haul freight.",
      action: "Track LNG truck sales, electric truck penetration, and freight activity by province.",
      access: "Indexed headline; Reuters access may be required",
      url: "https://news.google.com/search?q=%22China%20sets%20sights%20on%20heavy%20truck%20electrification%20in%20blow%20to%20diesel%20demand%22%20Reuters",
    },
    {
      date: "2026-06-09",
      source: "Reuters",
      factorId: "power-weather",
      bias: "Supports LNG demand",
      biasTone: "support",
      headline: "LNG demand in Asia recovers from Iran shock as China buys",
      readthrough: "Chinese buying was cited as part of an Asian demand recovery after Middle East disruption.",
      action: "Compare spot price moves with Chinese cargo arrivals and summer power-sector gas demand.",
      access: "Indexed headline; Reuters access may be required",
      url: "https://news.google.com/search?q=%22LNG%20demand%20in%20Asia%20recovers%20from%20Iran%20shock%20as%20China%20buys%22%20Reuters",
    },
    {
      date: "2026-06-08",
      source: "Bloomberg",
      factorId: "power-weather",
      bias: "Supports LNG demand",
      biasTone: "support",
      headline: "China Ramping Up LNG Buying in Anticipation of Summer Heat",
      readthrough: "Summer cooling demand can lift gas-fired power burn and prompt LNG restocking.",
      action: "Monitor weather, power burn, and coastal terminal sendout for confirmation.",
      access: "Indexed headline; Bloomberg access may be required",
      url: "https://news.google.com/search?q=%22China%20Ramping%20Up%20LNG%20Buying%20in%20Anticipation%20of%20Summer%20Heat%22%20Bloomberg",
    },
    {
      date: "2026-06-01",
      source: "Bloomberg",
      factorId: "power-weather",
      bias: "Supports LNG demand",
      biasTone: "support",
      headline: "China's LNG Imports Rebound in May as Buyers Prepare for Summer",
      readthrough: "A May import rebound points to seasonal preparation for warmer-weather demand.",
      action: "Check whether May rebound is sustained into June and July or remains seasonal restocking.",
      access: "Indexed headline; Bloomberg access may be required",
      url: "https://news.google.com/search?q=%22China%27s%20LNG%20Imports%20Rebound%20in%20May%20as%20Buyers%20Prepare%20for%20Summer%22%20Bloomberg",
    },
    {
      date: "2026-05-26",
      source: "Global LNG Hub",
      factorId: "supply-mix",
      bias: "Caps spot LNG",
      biasTone: "cap",
      headline: "Russian gas exports to China expand as pipelines and LNG reshape supply routes",
      readthrough: "More Russian pipeline and LNG optionality can reduce China's need for non-Russian spot LNG when economics favor alternatives.",
      action: "Track Power of Siberia nominations and Russian LNG arrivals by receiving terminal.",
      access: "Direct public report page",
      url: "https://globallnghub.com/report-presentation/russian-gas-exports-to-china-expand-as-pipelines-and-lng-reshape-supply-routes",
    },
    {
      date: "2026-05-15",
      source: "S&P Global",
      factorId: "trade-sanctions",
      bias: "Supports supply diversity",
      biasTone: "support",
      headline: "Trump says China wants to buy US oil and LNG after Beijing talks",
      readthrough: "A US-China trade thaw could reopen US LNG flows into China and improve portfolio flexibility.",
      action: "Watch for tariff relief, resumed US cargoes, and term-contract nominations into Chinese terminals.",
      access: "Indexed headline; S&P Global access may be required",
      url: "https://news.google.com/search?q=%22Trump%20says%20China%20wants%20to%20buy%20US%20oil%20and%20LNG%20after%20Beijing%20talks%22%20%22S%26P%20Global%22",
    },
    {
      date: "2026-04-16",
      source: "EIA",
      factorId: "global-balance",
      bias: "Supports affordability",
      biasTone: "support",
      headline: "US natural gas exports to grow nearly 30% by 2027 as LNG facilities ramp up",
      readthrough: "More US LNG supply can ease global balances over time, improving price affordability for flexible Chinese buyers.",
      action: "Track US project ramp-ups and destination-flexible cargo availability into Asia.",
      access: "Direct public source",
      url: "https://www.eia.gov/todayinenergy/detail.php?id=64924",
    },
    {
      date: "2026-04-14",
      source: "Rystad Energy",
      factorId: "price-affordability",
      bias: "Mixed / buyer risk",
      biasTone: "risk",
      headline: "Asia's Energy Buyers: Between a Rock and a Hard Place",
      readthrough: "Regional buyers face price, supply-security, and policy tradeoffs that shape China's spot LNG participation.",
      action: "Use as context for Chinese buyer sensitivity to price, security, and shipping constraints.",
      access: "Indexed headline; direct page not server-rendered in scan",
      url: "https://news.google.com/search?q=%22Asia%27s%20Energy%20Buyers%3A%20Between%20a%20Rock%20and%20a%20Hard%20Place%22%20%22Rystad%20Energy%22",
    },
    {
      date: "2026-03-11",
      source: "Global LNG Hub",
      factorId: "supply-security",
      bias: "Risk supportive",
      biasTone: "risk",
      headline: "Strait of Hormuz disruption could reshape China's LNG supply security",
      readthrough: "Hormuz risk can lift security-driven stocking and diversification, while also raising spot prices.",
      action: "Stress-test China exposure to Qatar and Middle East LNG against pipeline and Russian supply alternatives.",
      access: "Direct public report page",
      url: "https://globallnghub.com/report-presentation/strait-of-hormuz-disruption-could-reshape-chinas-lng-supply-security",
    },
    {
      date: "2026-03-04",
      source: "ICIS",
      factorId: "macro-policy",
      bias: "Policy context",
      biasTone: "context",
      headline: "What to watch for energy policy in China's Two Sessions",
      readthrough: "Energy policy signals can affect gas pricing, infrastructure, and import appetite, but need confirmation in data.",
      action: "Check gas pricing, import, and infrastructure policy signals against demand-side assumptions.",
      access: "Indexed headline; ICIS access may be required",
      url: "https://news.google.com/search?q=%22What%20to%20watch%20for%20energy%20policy%20in%20China%27s%20Two%20Sessions%22%20ICIS",
    },
    {
      date: "2026-03-03",
      source: "S&P Global",
      factorId: "price-affordability",
      bias: "Caps spot LNG",
      biasTone: "cap",
      headline: "China faces LNG supply test amid Middle East crisis, spot price increase",
      readthrough: "Middle East disruption and higher spot prices test China's willingness to buy prompt LNG.",
      action: "Watch spot price ceilings for Chinese buyers and any switch toward pipelines or domestic gas.",
      access: "Indexed headline; S&P Global access may be required",
      url: "https://news.google.com/search?q=%22China%20faces%20LNG%20supply%20test%20amid%20Middle%20East%20crisis%2C%20spot%20price%20increase%22%20%22S%26P%20Global%22",
    },
    {
      date: "2026-02-12",
      source: "ICIS",
      factorId: "transport",
      bias: "Caps LNG demand",
      biasTone: "cap",
      headline: "China's shift to electric heavy trucks pressures LNG use in transport",
      readthrough: "Electric heavy trucks reduce one of the more price-responsive pockets of LNG demand.",
      action: "Review whether road-fuel LNG weakness changes city-gas and transport demand allocation assumptions.",
      access: "Indexed headline; ICIS access may be required",
      url: "https://news.google.com/search?q=%22China%27s%20shift%20to%20electric%20heavy%20trucks%20pressures%20LNG%20use%20in%20transport%22%20ICIS",
    },
    {
      date: "2026-01-23",
      source: "IEA",
      factorId: "global-balance",
      bias: "Context",
      biasTone: "context",
      headline: "Growth in global demand for natural gas is set to accelerate in 2026 as LNG wave spreads through markets",
      readthrough: "The LNG supply wave can change China's spot affordability, but stronger global demand can absorb part of the looseness.",
      action: "Use IEA global balance assumptions as a cross-check on JKM affordability scenarios.",
      access: "Direct public source",
      url: "https://www.iea.org/news/growth-in-global-demand-for-natural-gas-is-set-to-accelerate-in-2026-as-lng-wave-spreads-through-markets",
    },
    {
      date: "2026-07-08",
      source: "GIIGNL",
      factorId: "global-balance",
      bias: "Context",
      biasTone: "context",
      headline: "GIIGNL annual report library refreshed with latest LNG market report PDFs",
      readthrough: "GIIGNL provides importer rankings, global trade totals, and China share context for periodic monitor refreshes.",
      action: "Use GIIGNL for annual import-share benchmarking and global trade context.",
      access: "Direct public report page and PDFs",
      url: "https://giignl.org/annual-report/",
    },
    {
      date: "2026-07-09",
      source: "LinkedIn / Greg Molnar",
      factorId: "expert-commentary",
      bias: "Manual review",
      biasTone: "manual",
      headline: "Greg Molnar LinkedIn posts require authenticated/manual review",
      readthrough: "The requested LinkedIn profile and recent-activity URL blocked unauthenticated fetches with HTTP 999, so no post text was captured in this automated scan.",
      action: "Open the profile while logged in and add any China LNG post summaries during the next manual monitor pass.",
      access: "Manual profile link",
      url: "https://www.linkedin.com/in/greg-moln%C3%A1r-38601171/",
    },
  ],
};
